const RESOURCE_CATALOG = [
  {
    "id": "B01",
    "title": "El poder del ahora",
    "thematic": "Regulación Emocional",
    "format": "Libro",
    "description": "Guía de presencia mental y reducción de rumiación.",
    "level": "Amarillo",
    "validation": "Recurso de biblioterapia revisado para psicoeducación.",
    "author": "E. Tolle",
    "source": null,
    "isInstitutional": false,
    "content": "Recurso orientado a fortalecer la presencia mental, observar pensamientos repetitivos y practicar pausas de atención plena. Úsalo como apoyo preventivo o complementario cuando notes rumiación o preocupación constante."
  },
  {
    "id": "B02",
    "title": "Mindfulness para principiantes",
    "thematic": "Ansiedad",
    "format": "Libro/Audio",
    "description": "Técnicas de atención plena para manejar estrés cotidiano.",
    "level": "Verde",
    "validation": "Basado en prácticas de mindfulness ampliamente usadas en bienestar emocional.",
    "author": "J. Kabat-Zinn",
    "source": null,
    "isInstitutional": false,
    "content": "Introduce prácticas breves de respiración consciente, observación del cuerpo y atención al presente. Puede usarse para mantener bienestar emocional y reducir activación fisiológica leve."
  },
  {
    "id": "B03",
    "title": "Podcast: La mente en calma",
    "thematic": "Estrés",
    "format": "Audio/Podcast",
    "description": "Episodios breves con estrategias de regulación emocional.",
    "level": "Verde",
    "validation": "Psicoeducación preventiva en formato breve.",
    "author": null,
    "source": null,
    "isInstitutional": false,
    "content": "Serie de audios cortos para acompañar pausas de descanso, manejo de pensamientos acelerados y organización de rutinas durante semanas académicas exigentes."
  },
  {
    "id": "B04",
    "title": "Curso: Gestión emocional en 7 días",
    "thematic": "Regulación Emocional",
    "format": "Video/Interactivo",
    "description": "Micro-lecciones con ejercicios prácticos y registro de progreso.",
    "level": "Amarillo",
    "validation": "Contenido psicoeducativo estructurado para autorregulación.",
    "author": null,
    "source": null,
    "isInstitutional": false,
    "content": "Plan corto de ejercicios para reconocer emociones, identificar detonantes, practicar respiración y organizar acciones de autocuidado durante una semana."
  },
  {
    "id": "B05",
    "title": "App: Sanvello",
    "thematic": "Ansiedad",
    "format": "Herramienta Digital",
    "description": "Seguimiento de ánimo, CBT guiada y ejercicios de respiración.",
    "level": "Naranja",
    "validation": "Herramienta digital complementaria basada en principios CBT.",
    "author": null,
    "source": null,
    "isInstitutional": false,
    "content": "Recurso digital complementario para seguimiento emocional, ejercicios guiados y prácticas de respiración. No sustituye atención profesional cuando hay malestar significativo."
  },
  {
    "id": "B06",
    "title": "Espacio: Sala de Bienestar UTB",
    "thematic": "Hábitos Saludables",
    "format": "Espacio Físico/Institucional",
    "description": "Lugar silencioso para lectura, meditación y desconexión en campus.",
    "level": "Verde",
    "validation": "Recurso institucional UTB.",
    "author": null,
    "source": null,
    "isInstitutional": true,
    "content": "Espacio físico sugerido para pausas, lectura tranquila, respiración y desconexión. Recomendado como recurso de mantenimiento y prevención dentro del campus."
  },
  {
    "id": "B07",
    "title": "Cuando el cuerpo dice no",
    "thematic": "Estrés/Cuerpo",
    "format": "Libro",
    "description": "Exploración del vínculo entre estrés crónico y salud física.",
    "level": "Naranja",
    "validation": "Biblioterapia complementaria para reflexión sobre estrés crónico.",
    "author": "G. Maté",
    "source": null,
    "isInstitutional": false,
    "content": "Recurso de lectura para comprender cómo el estrés sostenido puede relacionarse con malestar físico. Debe usarse como apoyo paralelo si ya existe recomendación profesional."
  },
  {
    "id": "B08",
    "title": "Taller: Primeros auxilios psicológicos",
    "thematic": "Crisis/Prevención",
    "format": "Video/Institucional",
    "description": "Protocolo básico de contención emocional para pares y autocuidado.",
    "level": "Naranja",
    "validation": "Recurso institucional y preventivo.",
    "author": null,
    "source": null,
    "isInstitutional": true,
    "content": "Material introductorio sobre escucha, contención, identificación de señales de alerta y rutas de apoyo. Útil para reconocer cuándo buscar ayuda inmediata."
  },
  {
    "id": "B09",
    "title": "Guía: Higiene del sueño universitario",
    "thematic": "Sueño",
    "format": "PDF/Interactivo",
    "description": "Rutinas para mejorar descanso y rendimiento académico.",
    "level": "Verde",
    "validation": "Psicoeducación preventiva para hábitos saludables.",
    "author": null,
    "source": null,
    "isInstitutional": false,
    "content": "Guía práctica con horarios de sueño, reducción de pantallas antes de dormir, planificación de estudio y señales para consultar si el problema persiste."
  },
  {
    "id": "B10",
    "title": "Biblioteca UTB – Zona de Calma",
    "thematic": "Hábitos Saludables",
    "format": "Espacio Físico/Institucional",
    "description": "Área designada para lectura tranquila y desconexión digital.",
    "level": "Verde",
    "validation": "Recurso institucional UTB.",
    "author": null,
    "source": null,
    "isInstitutional": true,
    "content": "Espacio sugerido para pausas de lectura, concentración y desconexión. Puede complementar el diario emocional y las rutinas de autocuidado."
  },
  {
    "id": "B11",
    "title": "Ansiedad: cómo enfrentarla",
    "thematic": "Ansiedad",
    "format": "Libro",
    "description": "Estrategias prácticas basadas en terapia cognitivo-conductual.",
    "level": "Amarillo",
    "validation": "Biblioterapia con enfoque CBT.",
    "author": "F. Sarramona",
    "source": null,
    "isInstitutional": false,
    "content": "Lectura de apoyo con herramientas para identificar pensamientos ansiosos, cuestionarlos y aplicar conductas de afrontamiento saludables."
  },
  {
    "id": "B12",
    "title": "Audio: Respiración 4-7-8 guiada",
    "thematic": "Regulación Emocional",
    "format": "Audio",
    "description": "Técnica de respiración para reducir activación fisiológica en 3 minutos.",
    "level": "Verde",
    "validation": "Ejercicio de respiración usado en autorregulación emocional.",
    "author": null,
    "source": null,
    "isInstitutional": false,
    "content": "Ejercicio breve: inhalar 4 segundos, sostener 7 y exhalar 8. Repite varias rondas en un lugar seguro y cómodo."
  },
  {
    "id": "B13",
    "title": "Video: Manejo del estrés académico",
    "thematic": "Estrés",
    "format": "Video",
    "description": "Consejos para estudiantes universitarios.",
    "level": "Amarillo",
    "validation": "Psicoeducación para población universitaria.",
    "author": null,
    "source": null,
    "isInstitutional": false,
    "content": "Video con estrategias para dividir tareas, priorizar pendientes, cuidar pausas y reconocer cuándo el estrés académico requiere apoyo adicional."
  },
  {
    "id": "B14",
    "title": "App: Woebot",
    "thematic": "Regulación Emocional",
    "format": "Herramienta Digital",
    "description": "Conversaciones guiadas con IA basada en principios CBT.",
    "level": "Naranja",
    "validation": "Herramienta digital complementaria basada en CBT.",
    "author": null,
    "source": null,
    "isInstitutional": false,
    "content": "Herramienta complementaria para identificar pensamientos y practicar reestructuración cognitiva básica. No reemplaza atención psicológica."
  },
  {
    "id": "B15",
    "title": "Guía: Autocompasión en tiempos difíciles",
    "thematic": "Autoestima",
    "format": "PDF",
    "description": "Ejercicios de autocompasión adaptados al contexto universitario.",
    "level": "Amarillo",
    "validation": "Ejercicios adaptados de psicoeducación en autocompasión.",
    "author": null,
    "source": null,
    "isInstitutional": false,
    "content": "Guía con ejercicios para reconocer sufrimiento sin juicio, hablarse con amabilidad y construir acciones pequeñas de cuidado durante periodos difíciles."
  },
  {
    "id": "B16",
    "title": "Contactos de emergencia y apoyo inmediato",
    "thematic": "Crisis/Prevención",
    "format": "Espacio Físico/Institucional",
    "description": "Línea 192, Línea 123 y Psicología UTB para situaciones de crisis.",
    "level": "Rojo",
    "validation": "Rutas institucionales y nacionales de apoyo.",
    "author": null,
    "source": null,
    "isInstitutional": true,
    "content": "Si estás en peligro inmediato, llama al 123. También puedes contactar la Línea 192 de Salud Mental Colombia y Psicología UTB en bienestar@utb.edu.co. Tu vida es valiosa y no tienes que afrontar esto solo/a."
  }
];

module.exports = { RESOURCE_CATALOG };
